### ISSUE TITLE
rbac模块和nestedSets模块设置使用的表名有bug

### ISSUE THREAD

**Issue by zhengyc9090** [gmars/tp5-rbac#1]
在rbac模块中使用tp的  Db::name()  方法，到nestedSets模块中却使用了Db::table方法，问题就是，使用name方法会自动读取配置中的表前缀，而nestedSets中却又使用无前缀表名。这就导致了两个包依赖使用的表名始终无法统一。

**Comment by gmars** [comment]
感谢指出，在tp5.1中也发现了其他的bug本地有修复但是最近太忙了没有提交。

**Comment by zhang123peng** [comment]
你上面的bug是还没有修改是吧？

**Comment by gmars** [comment]
新版本已经修复了该bug
