### ISSUE TITLE
权限分组第一次创建ID为4

### ISSUE THREAD

**Issue by 496672097** [gmars/tp5-rbac#10]
![图片](https://user-images.githubusercontent.com/20740855/56449799-08a45900-6351-11e9-8203-522555e70205.png)
![图片](https://user-images.githubusercontent.com/20740855/56449802-178b0b80-6351-11e9-9924-51aed3a005c9.png)
这个不是太懂为什么

**Comment by gmars** [comment]
这个是因为sql中AUTO_INCREMENT=4这句导致的从4开始递增。影响不大，你可以自己修改permission_category这个表的id递增初始值【但是要注意防止和当前已添加的数据id重复】。如果对现有业务有影响的话请删除vendor目录重新composer install然后删除/runtime/rbac_sql.lock后重新创建表。我已经修改了id的问题

**Comment by nongzhenli** [comment]
@gmars 前辈，请问下，权限分组的应用场景一般是做什么用的呢？

**Comment by gmars** [comment]
> @gmars 前辈，请问下，权限分组的应用场景一般是做什么用的呢？

一般当权限节点非常多时进行分组管理和选择比较方便

**Comment by nongzhenli** [comment]
> > @gmars 前辈，请问下，权限分组的应用场景一般是做什么用的呢？
> 
> 一般当权限节点非常多时进行分组管理和选择比较方便

好嘞！明白了，谢谢~
