### ISSUE TITLE
关于 Class 'think\facade\Env' not found

### ISSUE THREAD

**Issue by nongzhenli** [gmars/tp5-rbac#11]
你好，我使用
`createTable`
初始化数据库表，提示报错：

>  Class 'think\facade\Env' not found
我使用的是 thinkphp5.024 
这个是类库是不是仅支持 5.1呀？我是需要升级5.1才能解决这个问题嘛？

**Comment by gmars** [comment]
是的  5.0.*没有Evn可以找到包的CreateTable.php文件找到env的位置改为自己runtime的路径
