### ISSUE TITLE
Permission 96行，在两个不同浏览器中登录同一个账号会获取不到权限

### ISSUE THREAD

**Issue by KouSum** [gmars/tp5-rbac#12]
$permission = Cache::get($this->_permissionCachePrefix . $userId);

        if (!empty($permission)) {
            return $permission;
        }

**Comment by gmars** [comment]
因为使用cache来存储用户权限数据的不会存在获取不到的情况。检查下两个浏览器对cookie的支持。可以看看在获取权限前userid是否能取到。
