### ISSUE TITLE
登录时，查询用户的权限存入缓存

### ISSUE THREAD

**Issue by xx9090950** [gmars/tp5-rbac#4]
在用户登录的时候查询出用户的权限，存入缓存，以便后面的访问做权限验证的时候，不用反复查库。但是，在存入缓存的时候，使用了一个写死的缓存名，也就是permission。当用户A登录后查询拥有 权限1。紧接着管理员登录，查询到权限123456789 就会覆盖掉前面的缓存。使用户A也拥有了管理员的权限
建议：
-可以把cache 替换为session
-根据用户id，生成一个动态的缓存名

**Comment by gmars** [comment]
该问题已修复，谢谢。采用你的方案cache名称存入session的解决方案。增加config中可配置项permission_cache_prefix用于区分权限缓存前缀。
