### ISSUE TITLE
composer update也无法安装， 可能是因为我的TP5是5.1版本的吗

### ISSUE THREAD

**Issue by NightLostK** [gmars/tp5-rbac#6]
下面是错误信息
**composer update**
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gmars/tp5-rbac dev-master -> satisfiable by gmars/tp5-rbac[dev-master].
    - gmars/tp5-rbac dev-master requires gmars/tp5-nestedsets dev-master -> satisfiable by gmars/tp5-nestedsets[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by NightLostK** [comment]
我的composer里面：
"require": {
        "php": ">=5.6.0",
        "topthink/framework": "5.1.*",
        "gmars/tp5-rbac": "dev-master"
    },

**Comment by NightLostK** [comment]
> 下面是错误信息
> **composer update**
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Installation request for gmars/tp5-rbac dev-master -> satisfiable by gmars/tp5-rbac[dev-master].
> - gmars/tp5-rbac dev-master requires gmars/tp5-nestedsets dev-master -> satisfiable by gmars/tp5-nestedsets[dev-master] but these conflict with your requirements or minimum-stability.

解决了， 原来是要先装 gmars/tp5-nestedsets

**Comment by NightLostK** [comment]
> 下面是错误信息
> **composer update**
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Installation request for gmars/tp5-rbac dev-master -> satisfiable by gmars/tp5-rbac[dev-master].
> - gmars/tp5-rbac dev-master requires gmars/tp5-nestedsets dev-master -> satisfiable by gmars/tp5-nestedsets[dev-master] but these conflict with your requirements or minimum-stability.

解决了：
不是TP版本的原因， composer.json中这样添加就行：
"require": {
        "php": ">=5.6.0",
        "topthink/framework": "5.1.*",
        "gmars/tp5-nestedsets": "dev-master",
        "gmars/tp5-rbac": "dev-master"
    },

**Comment by NightLostK** [comment]
php think migrate:run  运行之后显示：
All Done. Took 0.1197s, 但是只生成了一个表 migrations

**Comment by gmars** [comment]
migrate有问题，如果迁移不成功使用库中的sql文件来生成。[sql文件的地址在](https://github.com/gmars/tp5-rbac/blob/master/gmars_rbac.sql)https://github.com/gmars/tp5-rbac/blob/master/gmars_rbac.sql

**Comment by NightLostK** [comment]
请问下, role 角色表中的 左值 右值是什么意思= =

**Comment by gmars** [comment]
新版本修复了该问题，启用了角色的继承所以没有左右值及父级id了
