### ISSUE TITLE
如果表有前缀，会导致很多错误，此项目还在维护么

### ISSUE THREAD

**Issue by mengyonghang** [gmars/tp5-rbac#7]
class NestedSets 下
private $prefix; //表前缀
public function __construct{...
$this->prefix =Env::get('database.prefix','');
        //如果是表名则处理配置
        if (is_string($dbTarg)) {
            $this->tableName = $this->prefix.$dbTarg;
        }
如此处理，可以把表前缀加上，但是还是会报错。
--------
variable type error： boolean

是不是意思是返回类型不能为 布尔值？

修改：
public function insert($parentId, array $data = [], $position = "top")
下 的返回：
return true; 改为 return 1；
可以正常。
请问此项目还在维护么？

**Comment by gmars** [comment]
新版本已经修复了该问题
