### ISSUE TITLE
can方法的问题

### ISSUE THREAD

**Issue by 496672097** [gmars/tp5-rbac#8]
can方法使用的是读取SESSION的方式 ， 但是使用JWT 是无法验证权限的。 希望大佬能改一下can方法，能输入访问路径，已经读取用户名需要传入的方式。 这样就绕过了必须读取session 的方式。 在线等 急！

**Comment by gmars** [comment]
这个在修改今天或明天发布新版本

**Comment by 496672097** [comment]
十分感谢， 然而你是今天早上凌晨3点在更新版本？？？？？？程序员都不需要睡觉的吗

**Comment by gmars** [comment]
@496672097 已经发布了2.0版本可以使用composer安装了。readme中有jwt使用说明
