### ISSUE TITLE
新版本2.0数据迁移有问题

### ISSUE THREAD

**Issue by 496672097** [gmars/tp5-rbac#9]
Syntax error or access violation: 1072 Key column 'left_key' doesn't exist in table
错误如上， 查看迁移内容：1、中存在表面带##号问题， 2、Syntax error or access violation: 1072 Key column 'left_key' doesn't exist in table
外键错误， 您可以测试一下，删除表， 重新request 一个TP5 然后安装。此问题就会出现。望能解决，十分感谢。最后，是一个建议。某些系统权限可能需要一个管理员权限。 再验证token的时候generateToken()方法中是否能再foreach之后添加一个特殊权限，用于验证超级管理员（后门管理员）

**Comment by 496672097** [comment]
DROP TABLE IF EXISTS `###role`;
CREATE TABLE `###role` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '角色名',
  `description` varchar(200) NOT NULL DEFAULT '' COMMENT '角色描述',
  `status` smallint(4) unsigned NOT NULL DEFAULT '0' COMMENT '状态1正常0未启用',
  `sort_num` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '排序值',
  PRIMARY KEY (`id`),
  KEY `idx_role` (`status`,`left_key`,`right_key`,`level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色';

**Comment by 496672097** [comment]
public function generateToken($userId, $timeOut = 7200, $prefix = '')
    {
        $token = md5($prefix . $this->randCode(32) . $this->saltToken . time());
        $freshTOken = md5($prefix . $this->randCode(32) . $this->saltToken . time());
        $permissionModel = new Permission($this->db);
        $permission = $permissionModel->getPermissionByUserId($userId);
        //无权限时为登录验证用
        if (!empty($permission)) {
            $newPermission = [];
            if (!empty($permission)) {
                foreach ($permission as $k=>$v)
                {
                    $newPermission[$v['path']] = $v;
                }
                //insert admin power changed by chenyifu 2019-04-18
                //$newPermission[admin['path']] = "All";
            }
            Cache::set($token, $newPermission, $timeOut);
        } else {
            //权限为空时token仅仅用作登录身份验证
            Cache::set($token, '', $timeOut);
        }
        Cache::set($freshTOken, $token, $timeOut);
        return [
            'token' => $token,
            'refresh_token' => $freshTOken,
            'expire' => $timeOut
        ];
    }

**Comment by 496672097** [comment]
跪求码大神，帮忙!将十分感谢！！！

**Comment by 496672097** [comment]
我自己修改的sql如下， 
CREATE TABLE `###role` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '角色名',
  `description` varchar(200) NOT NULL DEFAULT '' COMMENT '角色描述',
  `status` smallint(4) unsigned NOT NULL DEFAULT '0' COMMENT '状态1正常0未启用',
  `sort_num` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '排序值',
  `left_key` varchar(200) NOT NULL DEFAULT '0' COMMENT '未知数值',
  `right_key` varchar(200)  NOT NULL DEFAULT '0' COMMENT '未知数值',
  `level` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '排序值',
  PRIMARY KEY (`id`),
  KEY `idx_role` (`status`,`left_key`,`right_key`,`level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色';

不知道是否正确

**Comment by 496672097** [comment]
修改后，缺少private $userTable; 在rbac.php的class中。会导致创建用户失败

**Comment by gmars** [comment]
role表的left_key和right_key的问题修复了。你需要更新下重新生成数据表。表名中的###请保留。这是为了替换成数据库的表前缀保留的替换字符串。

**Comment by gmars** [comment]
另外createUser方法在新版中已经废除。因为每个系统对用户信息的要求不同所以用户管理需要自行实现。 @496672097
